### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by juliatiemi** [groupinho/XPSimulation#1]
Features:

- User register: name, email, password and a short description are required; The user may or may not upload a photo 
- Log in: only users can post and answer questions
- An user must be able to delete his/her account
- An user must be able to change his/her password

**Comment by vbuxbaum** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPRINT 1 -------------------------------](https://trello.com/c/0jUyrXkb/9-sprint-1)
